### ISSUE TITLE
Не работает менеджер модели EmployerManager при создании объекта из формы.

### ISSUE THREAD

**Issue by thunderamur** [testpass1982/bewelder_redesign#55]
https://github.com/thunderamur/bewelder_redesign/blob/orgs/orgs/models.py
EmployerManager не работает при создании объекта через форму.

https://github.com/thunderamur/bewelder_redesign/blob/orgs/orgs/tests/test_views.py
test_create_employer не проходит
`        self.assertEqual(
            response.context['employer'].name,
            response.context['employer'].short_name,
)`

Но при этом проходит тест модели
https://github.com/thunderamur/bewelder_redesign/blob/orgs/orgs/tests/test_models.py
test_creation_short_name
`self.assertEqual(self.employer_1.name, self.employer_1.short_name)`

Т.о. получается, что Employer.objects.create создает объект правильно через EmployerManager, а при создании через форму идет мимо EmployerManager.

**Comment by thunderamur** [comment]
Можно, конечно, просто сделать обязательным поле на форме, но хочется разобраться в вопросе.

**Comment by machine23** [comment]
Моделформы не используют `create`. Тут либо переопределять метод `save` у модели, или (что, наверное, лучше) в самой форме задать нужную логику при очистке данных формы (переопределить метод `clean` формы). Т.е. в методе `clean` задать проверку, пришло ли нужное значение для `short_name` и, если нет, назначить этому полю нужное значение.

**Comment by thunderamur** [comment]
Василий, спасибо за информацию!
